version: "3"
services:
  vpn:
    image: bubuntux/nordvpn
    network_mode: bridge        # Required
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=USERNAME     # Required
      - "PASS=PASSWD"         # Required
      - CONNECT=United_Kingdom
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24,172.30.1.0/16
    ports:
      - 8080:80

  rutorrent:
    image: linuxserver/rutorrent
    container_name: rutorrent
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /path/to/config:/config
      - /path/to/downloads:/downloads
    restart: unless-stopped
